### ISSUE TITLE
Add custom server- or channel-specific commands

### ISSUE THREAD

**Issue by ghost** [zeyla/nanobot#28]
Commands should be able to be created by those with the "Manage Server" permission.

I can think of only these as being useful to people without the ability of causing harm:
- array
- base64
- binascii
- binhex
- bz2
- calendar
- cmath
- collections
- colorsys
- datetime
- decimal
- difflib
- enum
- fractions
- json (disallow I/O)
- keyword
- mimetypes
- numbers
- pprint
- random
- re
- string
- time
- types

Disallowing the usage of open() is _necessary_, as well as all of these libs' I/O related functions.
Users _must not_ be able to import modules.
There _should_ be a timeout of approximately 5 seconds on all commands.

**Comment by zeyla** [comment]
Not possible in Rust (#48). May open this in the future if I were to run Python and Rust side-by-side. Likely not going to happen.
